package ISO_3166.mappings is
   type Country_Enum is
                        (Afghanistan,
                         Albania,
                         Algeria,
                         American_Samoa,
                         Andorra,
                         Angola,
                         Anguilla,
                         Antarctica,
                         Antigua_and_Barbuda,
                         Argentina,
                         Armenia,
                         Aruba,
                         Australia,
                         Austria,
                         Azerbaijan,
                         Bahamas,
                         Bahrain,
                         Bangladesh,
                         Barbados,
                         Belarus,
                         Belgium,
                         Belize,
                         Benin,
                         Bermuda,
                         Bhutan,
                         Bolivia_Plurinational_State_of,
                         Bonaire_Sint_Eustatius_and_Saba,
                         Bosnia_and_Herzegovina,
                         Botswana,
                         Bouvet_Island,
                         Brazil,
                         British_Indian_Ocean_Territory,
                         Brunei_Darussalam,
                         Bulgaria,
                         Burkina_Faso,
                         Burundi,
                         Cabo_Verde,
                         Cambodia,
                         Cameroon,
                         Canada,
                         Cayman_Islands,
                         Central_African_Republic,
                         Chad,
                         Chile,
                         China,
                         Christmas_Island,
                         Cocos_Keeling_Islands,
                         Colombia,
                         Comoros,
                         Congo,
                         Congo_Democratic_Republic_of_the,
                         Cook_Islands,
                         Costa_Rica,
                         Croatia,
                         Cuba,
                         CuraÅao,
                         Cyprus,
                         Czechia,
                         CÅte_dIvoire,
                         Denmark,
                         Djibouti,
                         Dominica,
                         Dominican_Republic,
                         Ecuador,
                         Egypt,
                         El_Salvador,
                         Equatorial_Guinea,
                         Eritrea,
                         Estonia,
                         Eswatini,
                         Ethiopia,
                         Falkland_Islands_Malvinas,
                         Faroe_Islands,
                         Fiji,
                         Finland,
                         France,
                         French_Guiana,
                         French_Polynesia,
                         French_Southern_Territories,
                         Gabon,
                         Gambia,
                         Georgia,
                         Germany,
                         Ghana,
                         Gibraltar,
                         Greece,
                         Greenland,
                         Grenada,
                         Guadeloupe,
                         Guam,
                         Guatemala,
                         Guernsey,
                         Guinea,
                         GuineaBissau,
                         Guyana,
                         Haiti,
                         Heard_Island_and_McDonald_Islands,
                         Holy_See,
                         Honduras,
                         Hong_Kong,
                         Hungary,
                         Iceland,
                         India,
                         Indonesia,
                         Iran_Islamic_Republic_of,
                         Iraq,
                         Ireland,
                         Isle_of_Man,
                         Israel,
                         Italy,
                         Jamaica,
                         Japan,
                         Jersey,
                         Jordan,
                         Kazakhstan,
                         Kenya,
                         Kiribati,
                         Korea_Democratic_Peoples_Republic_of,
                         Korea_Republic_of,
                         Kuwait,
                         Kyrgyzstan,
                         Lao_Peoples_Democratic_Republic,
                         Latvia,
                         Lebanon,
                         Lesotho,
                         Liberia,
                         Libya,
                         Liechtenstein,
                         Lithuania,
                         Luxembourg,
                         Macao,
                         Madagascar,
                         Malawi,
                         Malaysia,
                         Maldives,
                         Mali,
                         Malta,
                         Marshall_Islands,
                         Martinique,
                         Mauritania,
                         Mauritius,
                         Mayotte,
                         Mexico,
                         Micronesia_Federated_States_of,
                         Moldova_Republic_of,
                         Monaco,
                         Mongolia,
                         Montenegro,
                         Montserrat,
                         Morocco,
                         Mozambique,
                         Myanmar,
                         Namibia,
                         Nauru,
                         Nepal,
                         Netherlands,
                         New_Caledonia,
                         New_Zealand,
                         Nicaragua,
                         Niger,
                         Nigeria,
                         Niue,
                         Norfolk_Island,
                         North_Macedonia,
                         Northern_Mariana_Islands,
                         Norway,
                         Oman,
                         Pakistan,
                         Palau,
                         Palestine_State_of,
                         Panama,
                         Papua_New_Guinea,
                         Paraguay,
                         Peru,
                         Philippines,
                         Pitcairn,
                         Poland,
                         Portugal,
                         Puerto_Rico,
                         Qatar,
                         Romania,
                         Russian_Federation,
                         Rwanda,
                         RÅunion,
                         Saint_BarthÅlemy,
                         Saint_Helena_Ascension_and_Tristan_da_Cunha,
                         Saint_Kitts_and_Nevis,
                         Saint_Lucia,
                         Saint_Martin_French_part,
                         Saint_Pierre_and_Miquelon,
                         Saint_Vincent_and_the_Grenadines,
                         Samoa,
                         San_Marino,
                         Sao_Tome_and_Principe,
                         Saudi_Arabia,
                         Senegal,
                         Serbia,
                         Seychelles,
                         Sierra_Leone,
                         Singapore,
                         Sint_Maarten_Dutch_part,
                         Slovakia,
                         Slovenia,
                         Solomon_Islands,
                         Somalia,
                         South_Africa,
                         South_Georgia_and_the_South_Sandwich_Islands,
                         South_Sudan,
                         Spain,
                         Sri_Lanka,
                         Sudan,
                         Suriname,
                         Svalbard_and_Jan_Mayen,
                         Sweden,
                         Switzerland,
                         Syrian_Arab_Republic,
                         Taiwan_Province_of_China,
                         Tajikistan,
                         Tanzania_United_Republic_of,
                         Thailand,
                         TimorLeste,
                         Togo,
                         Tokelau,
                         Tonga,
                         Trinidad_and_Tobago,
                         Tunisia,
                         Turkey,
                         Turkmenistan,
                         Turks_and_Caicos_Islands,
                         Tuvalu,
                         Uganda,
                         Ukraine,
                         United_Arab_Emirates,
                         United_Kingdom_of_Great_Britain_and_Northern_Ireland,
                         United_States_Minor_Outlying_Islands,
                         United_States_of_America,
                         Uruguay,
                         Uzbekistan,
                         Vanuatu,
                         Venezuela_Bolivarian_Republic_of,
                         Viet_Nam,
                         Virgin_Islands_British,
                         Virgin_Islands_US,
                         Wallis_and_Futuna,
                         Western_Sahara,
                         Yemen,
                         Zambia,
                         Zimbabwe,
                         Åland_Islands);
   Country_Enum_2_Country_Code : constant array(Country_Enum)  of integer := 
      (Afghanistan=> 4,
       Albania=> 8,
       Algeria=> 12,
       American_Samoa=> 16,
       Andorra=> 20,
       Angola=> 24,
       Anguilla=> 660,
       Antarctica=> 10,
       Antigua_and_Barbuda=> 28,
       Argentina=> 32,
       Armenia=> 51,
       Aruba=> 533,
       Australia=> 36,
       Austria=> 40,
       Azerbaijan=> 31,
       Bahamas=> 44,
       Bahrain=> 48,
       Bangladesh=> 50,
       Barbados=> 52,
       Belarus=> 112,
       Belgium=> 56,
       Belize=> 84,
       Benin=> 204,
       Bermuda=> 60,
       Bhutan=> 64,
       Bolivia_Plurinational_State_of=> 68,
       Bonaire_Sint_Eustatius_and_Saba=> 535,
       Bosnia_and_Herzegovina=> 70,
       Botswana=> 72,
       Bouvet_Island=> 74,
       Brazil=> 76,
       British_Indian_Ocean_Territory=> 86,
       Brunei_Darussalam=> 96,
       Bulgaria=> 100,
       Burkina_Faso=> 854,
       Burundi=> 108,
       Cabo_Verde=> 132,
       Cambodia=> 116,
       Cameroon=> 120,
       Canada=> 124,
       Cayman_Islands=> 136,
       Central_African_Republic=> 140,
       Chad=> 148,
       Chile=> 152,
       China=> 156,
       Christmas_Island=> 162,
       Cocos_Keeling_Islands=> 166,
       Colombia=> 170,
       Comoros=> 174,
       Congo=> 178,
       Congo_Democratic_Republic_of_the=> 180,
       Cook_Islands=> 184,
       Costa_Rica=> 188,
       Croatia=> 191,
       Cuba=> 192,
       CuraÅao=> 531,
       Cyprus=> 196,
       Czechia=> 203,
       CÅte_dIvoire=> 384,
       Denmark=> 208,
       Djibouti=> 262,
       Dominica=> 212,
       Dominican_Republic=> 214,
       Ecuador=> 218,
       Egypt=> 818,
       El_Salvador=> 222,
       Equatorial_Guinea=> 226,
       Eritrea=> 232,
       Estonia=> 233,
       Eswatini=> 748,
       Ethiopia=> 231,
       Falkland_Islands_Malvinas=> 238,
       Faroe_Islands=> 234,
       Fiji=> 242,
       Finland=> 246,
       France=> 250,
       French_Guiana=> 254,
       French_Polynesia=> 258,
       French_Southern_Territories=> 260,
       Gabon=> 266,
       Gambia=> 270,
       Georgia=> 268,
       Germany=> 276,
       Ghana=> 288,
       Gibraltar=> 292,
       Greece=> 300,
       Greenland=> 304,
       Grenada=> 308,
       Guadeloupe=> 312,
       Guam=> 316,
       Guatemala=> 320,
       Guernsey=> 831,
       Guinea=> 324,
       GuineaBissau=> 624,
       Guyana=> 328,
       Haiti=> 332,
       Heard_Island_and_McDonald_Islands=> 334,
       Holy_See=> 336,
       Honduras=> 340,
       Hong_Kong=> 344,
       Hungary=> 348,
       Iceland=> 352,
       India=> 356,
       Indonesia=> 360,
       Iran_Islamic_Republic_of=> 364,
       Iraq=> 368,
       Ireland=> 372,
       Isle_of_Man=> 833,
       Israel=> 376,
       Italy=> 380,
       Jamaica=> 388,
       Japan=> 392,
       Jersey=> 832,
       Jordan=> 400,
       Kazakhstan=> 398,
       Kenya=> 404,
       Kiribati=> 296,
       Korea_Democratic_Peoples_Republic_of=> 408,
       Korea_Republic_of=> 410,
       Kuwait=> 414,
       Kyrgyzstan=> 417,
       Lao_Peoples_Democratic_Republic=> 418,
       Latvia=> 428,
       Lebanon=> 422,
       Lesotho=> 426,
       Liberia=> 430,
       Libya=> 434,
       Liechtenstein=> 438,
       Lithuania=> 440,
       Luxembourg=> 442,
       Macao=> 446,
       Madagascar=> 450,
       Malawi=> 454,
       Malaysia=> 458,
       Maldives=> 462,
       Mali=> 466,
       Malta=> 470,
       Marshall_Islands=> 584,
       Martinique=> 474,
       Mauritania=> 478,
       Mauritius=> 480,
       Mayotte=> 175,
       Mexico=> 484,
       Micronesia_Federated_States_of=> 583,
       Moldova_Republic_of=> 498,
       Monaco=> 492,
       Mongolia=> 496,
       Montenegro=> 499,
       Montserrat=> 500,
       Morocco=> 504,
       Mozambique=> 508,
       Myanmar=> 104,
       Namibia=> 516,
       Nauru=> 520,
       Nepal=> 524,
       Netherlands=> 528,
       New_Caledonia=> 540,
       New_Zealand=> 554,
       Nicaragua=> 558,
       Niger=> 562,
       Nigeria=> 566,
       Niue=> 570,
       Norfolk_Island=> 574,
       North_Macedonia=> 807,
       Northern_Mariana_Islands=> 580,
       Norway=> 578,
       Oman=> 512,
       Pakistan=> 586,
       Palau=> 585,
       Palestine_State_of=> 275,
       Panama=> 591,
       Papua_New_Guinea=> 598,
       Paraguay=> 600,
       Peru=> 604,
       Philippines=> 608,
       Pitcairn=> 612,
       Poland=> 616,
       Portugal=> 620,
       Puerto_Rico=> 630,
       Qatar=> 634,
       Romania=> 642,
       Russian_Federation=> 643,
       Rwanda=> 646,
       RÅunion=> 638,
       Saint_BarthÅlemy=> 652,
       Saint_Helena_Ascension_and_Tristan_da_Cunha=> 654,
       Saint_Kitts_and_Nevis=> 659,
       Saint_Lucia=> 662,
       Saint_Martin_French_part=> 663,
       Saint_Pierre_and_Miquelon=> 666,
       Saint_Vincent_and_the_Grenadines=> 670,
       Samoa=> 882,
       San_Marino=> 674,
       Sao_Tome_and_Principe=> 678,
       Saudi_Arabia=> 682,
       Senegal=> 686,
       Serbia=> 688,
       Seychelles=> 690,
       Sierra_Leone=> 694,
       Singapore=> 702,
       Sint_Maarten_Dutch_part=> 534,
       Slovakia=> 703,
       Slovenia=> 705,
       Solomon_Islands=> 90,
       Somalia=> 706,
       South_Africa=> 710,
       South_Georgia_and_the_South_Sandwich_Islands=> 239,
       South_Sudan=> 728,
       Spain=> 724,
       Sri_Lanka=> 144,
       Sudan=> 729,
       Suriname=> 740,
       Svalbard_and_Jan_Mayen=> 744,
       Sweden=> 752,
       Switzerland=> 756,
       Syrian_Arab_Republic=> 760,
       Taiwan_Province_of_China=> 158,
       Tajikistan=> 762,
       Tanzania_United_Republic_of=> 834,
       Thailand=> 764,
       TimorLeste=> 626,
       Togo=> 768,
       Tokelau=> 772,
       Tonga=> 776,
       Trinidad_and_Tobago=> 780,
       Tunisia=> 788,
       Turkey=> 792,
       Turkmenistan=> 795,
       Turks_and_Caicos_Islands=> 796,
       Tuvalu=> 798,
       Uganda=> 800,
       Ukraine=> 804,
       United_Arab_Emirates=> 784,
       United_Kingdom_of_Great_Britain_and_Northern_Ireland=> 826,
       United_States_Minor_Outlying_Islands=> 581,
       United_States_of_America=> 840,
       Uruguay=> 858,
       Uzbekistan=> 860,
       Vanuatu=> 548,
       Venezuela_Bolivarian_Republic_of=> 862,
       Viet_Nam=> 704,
       Virgin_Islands_British=> 92,
       Virgin_Islands_US=> 850,
       Wallis_and_Futuna=> 876,
       Western_Sahara=> 732,
       Yemen=> 887,
       Zambia=> 894,
       Zimbabwe=> 716,
       Åland_Islands=> 248);
end ISO_3166.mappings;
