name: Ada (GNAT)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild make git

    - name: Build
      run: >
        git clone https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes.git .obj/testdata &&
        make all SOURCES=.obj/testdata/all/all.xml

